import type { Metadata } from "next";
import { Geist, Geist_Mono,  Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import LoadingWrapper from "@/components/LoadingWrapper";

const sink = localFont({
  src: [
    {
      path: '../../public/fonts/Worktalk.otf',
      weight: '400'
    },
    {
      path: '../../public/fonts/Worktalk.otf',
      weight: '700'
    }
  ],
  variable: '--font-sink',
})

const telma = localFont({
  src: [
    {
      path: '../../public/fonts/Telma-Light.otf',
      weight: '400'
    },
    {
      path: '../../public/fonts/Telma-Bold.otf',
      weight: '700'
    }
  ],
  variable: '--font-telma',
})

const guzan = localFont({
  src: [
    {
      path: '../../public/fonts/guzan.otf',
      weight: '400'
    },
    {
      path: '../../public/fonts/guzan.otf',
      weight: '700'
    }
  ],
  variable: '--font-guzan',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Narendra Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${telma.variable} ${sink.variable} ${guzan.variable} ${inter.variable} antialiased`}
      >
        <LoadingWrapper>{children}</LoadingWrapper>
      </body>
    </html>
  );
}
